CREATE TABLE IF NOT EXISTS "guildChannelsTable" (
  "channelId" varchar(32) PRIMARY KEY NOT NULL,
  "wordOfDay" BOOLEAN NOT NULL DEFAULT FALSE,
  "wikiOfDay" BOOLEAN NOT NULL DEFAULT FALSE,
  "memeOfDay" BOOLEAN NOT NULL DEFAULT FALSE,
  "animemeOfDay" BOOLEAN NOT NULL DEFAULT FALSE,
  "awwnimemeOfDay" BOOLEAN NOT NULL DEFAULT FALSE,
  "awwOfDay" BOOLEAN NOT NULL DEFAULT FALSE,
  "autoDelete" BOOLEAN NOT NULL DEFAULT FALSE,

  "guildId" varchar(32) NOT NULL REFERENCES "guildsTable" ON UPDATE CASCADE ON DELETE CASCADE
);
