apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ${ENV}delete-lastplayed
  namespace: josh-apps
spec:
  schedule: "0 12 * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ${ENV}delete-lastplayed
              image: curlimages/curl:7.72.0
              envFrom:
                - secretRef:
                    name: ${ENV}cron-basic-auth
              args:
                - /bin/sh
                - -ec
                - "curl -u $USERNAME:$PASSWORD -X DELETE $API_URL/guilds/lastplayed"
          restartPolicy: OnFailure
