# apiVersion: batch/v1beta1
# kind: CronJob
# metadata:
#   name: ${ENV}minute-refresh-count
#   namespace: josh-apps
# spec:
#   schedule: "* * * * *"
#   failedJobsHistoryLimit: 1
#   successfulJobsHistoryLimit: 1
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           containers:
#             - name: ${ENV}minute-refresh-count
#               image: curlimages/curl:7.72.0
#               envFrom:
#                 - secretRef:
#                     name: ${ENV}cron-basic-auth
#               args:
#                 - /bin/sh
#                 - -ec
#                 - "curl -u $USERNAME:$PASSWORD -X PUT $API_URL/refresh/count/minute"
#           restartPolicy: OnFailure
