apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ${ENV}minute-reset-rolls
  namespace: josh-apps
spec:
  schedule: "* * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ${ENV}minute-reset-rolls
              image: curlimages/curl:7.72.0
              envFrom:
                - secretRef:
                    name: ${ENV}cron-basic-auth
              args:
                - /bin/sh
                - -ec
                - 'curl -u $USERNAME:$PASSWORD -H "Content-Type: application/json" -d "{ \"minute\": `date +\"%M\"` }" -X PATCH $API_URL/rolls/reset'
          restartPolicy: OnFailure
