const DIMENSIONS = Object.freeze({
  DEFAULT_HEIGHT_MIN: 350,
  DEFAULT_WIDTH_MIN: 225,
  BORDER_MIN: 1,
  DEFAULT_HEIGHT_MAX: 490,
  DEFAULT_WIDTH_MAX: 315,
  BORDER_MAX: 1.4,
});

module.exports = DIMENSIONS;
