module.exports = Object.freeze({
  MAX_CLAIM_HOUR: 23,
  MIN_CLAIM_HOUR: 0,
  MAX_CLAIM_MINUTE: 59,
  MIN_CLAIM_MINUTE: 0,
  MIN_RARITY_PERCENTAGE: 0,
  MAX_RARITY_PERCENTAGE: 500,
  MIN_WISHLIST_MULTIPLIER: 0,
  MAX_WISHLIST_MULTIPLIER: 100,
  MAX_SECONDS_CLAIM_WAIFU: 604800,
  MIN_SECONDS_CLAIM_WAIFU: 0,
  MIN_SECONDS_USER_CLAIM_CHARACTER: 0,
  MAX_SECONDS_USER_CLAIM_CHARACTER: 604800,
});
